name: lint format and test

on: [push]

jobs:
  lint-format-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install tox

    - name: Lint with flake8
      run: |
        tox -e lint

    - name: Check with black formatter
      run: |
        tox -e fmt-check

    - name: Test with pytest
      run: |
        tox -e py

  generate-mutants:
    needs: lint-format-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install tox

    - name: Run mutation tests
      run: |
        tox -e check-mutants

    - name: Generate mutation tests report
      if: always()
      run: |
        tox -e generate-mutmut-report

    - name: Upload mutation tests results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Mutation tests results
        path: mutmut_report.xml

  publish-mutation-test-results:
    needs: generate-mutants
    runs-on: ubuntu-latest
    if: success() || failure()

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish mutation test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: mutmut_report.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.11
        if: always()
        with:
          files: artifacts/**/*.xml
